customer_options:
  pv_adoption_type: solar_plus_storage
data_selection:
  input_path: "../HolisticElectricityModelData.jl/runs/20250326-county_ba_6_base_2020_future_5_ipps_1"
der_aggregator_options:
  frac_viu_cost_savings_as_revenue: 0.1
  incentive_curve: 1
hem_options:
  der_aggregation_use_case: der_aggregation_use_case
  der_use_case: der_use_case
  market_structure: wholesale_market
  supply_choice_use_case: null_use_case
ipp_options:
  ipp_algorithm: mppdcmer_transportation_storage
regulator_options:
  allowed_return_on_investment: 0.112
  net_metering_policy: excess_marginal_cost
  planning_reserve_margin: 0.129
  rate_design: time_of_use
  tou_suffix: NE2035
simulation_parameters:
  solver: Xpress