# ------------------------------------------------------------------------------
# Data Selection
# ------------------------------------------------------------------------------

data_selection:

  input_path: "../HolisticElectricityModelData.jl/runs/20241111_ba_6_base_2020_future_2_ipps_1/"

# ------------------------------------------------------------------------------
# Simulation Parameters
# ------------------------------------------------------------------------------

simulation_parameters:
  
  solver: "Xpress"

# ------------------------------------------------------------------------------
# Holistic Energy Model (HEM) model-wide options
# ------------------------------------------------------------------------------

hem_options:

  market_structure: "vertically_integrated_utility"
  der_use_case: "der_use_case"
  supply_choice_use_case: "null_use_case"
  der_aggregation_use_case: "der_aggregation_use_case"

# ------------------------------------------------------------------------------
# Independent Power Producer (IPP) options
# ------------------------------------------------------------------------------

ipp_options:

  ipp_algorithm: "mppdcmer_transportation_storage"

# ------------------------------------------------------------------------------
# Regulator options
# ------------------------------------------------------------------------------

regulator_options:

  rate_design: "flat_rate"
  net_metering_policy: "excess_retail_rate"


# ------------------------------------------------------------------------------
# Customer options
# ------------------------------------------------------------------------------
customer_options:

  pv_adoption_type: "solar_plus_storage"