# ------------------------------------------------------------------------------
# Data Selection
# ------------------------------------------------------------------------------

DataSelection:

  input_path: "../HolisticElectricityModelData.jl/runs/20241120-ba_ba_6_base_2020_future_15_ipps_1/"

# ------------------------------------------------------------------------------
# Simulation Parameters
# ------------------------------------------------------------------------------

SimulationParameters:
  
  solver: "Gurobi"

# ------------------------------------------------------------------------------
# Holistic Energy Model (HEM) model-wide options
# ------------------------------------------------------------------------------

HEMOptions:

  market_structure: "VIU"
  der_use_case: "DERAdoption"
  supply_choice_use_case: "NullUseCase"
  der_aggregation_use_case: "DERAggregation"

# ------------------------------------------------------------------------------
# Regulator options
# ------------------------------------------------------------------------------

Regulator:

  rate_design: "FlatRate"
  net_metering_policy: "ExcessRetailRate"
  tou_suffix : "NE2025"
  planning_reserve_margin : 0.129
  allowed_return_on_investment : 0.112

# ------------------------------------------------------------------------------
# Independent Power Producer (IPP) options
# ------------------------------------------------------------------------------

IPPGroup:

  ipp_algorithm: "MPPDCMERTransStorage"

# ------------------------------------------------------------------------------
# Customer options
# ------------------------------------------------------------------------------
CustomerGroup:

  pv_adoption_type: "CompeteDERConfigs"

# ------------------------------------------------------------------------------
# DER Aggregator options
# ------------------------------------------------------------------------------
DERAggregator:

  incentive_curve: 1
  frac_viu_cost_savings_as_revenue: 0.5