# ------------------------------------------------------------------------------
# Solver 
# ------------------------------------------------------------------------------

# CHOOSE ONE
solver: "Gurobi", "Xpress"

# ------------------------------------------------------------------------------
# Data Selection
# ------------------------------------------------------------------------------

# Geography --------------------------------------------------------------------
# Currently, geography is tied to ReEDS balancing areas (BAs). Valid values are
# "p1", "p2", ..., "p134". This map shows where the BAs are located: 
# https://www.nrel.gov/analysis/assets/pdfs/reeds-model-regions-map.pdf.

# HEM analyses have been conducted for:
#     Nevada: "p13", "p14"
#     New England: "p129", "p130", "p131", "p132", "p133", "p134"

# EDIT
balancing_areas:
  - "p129"
  - "p130"
  - "p131"
  - "p132"
  - "p133"
  - "p134"

# Time -------------------------------------------------------------------------

base_year: 2020
num_future_years: 10

# Number of IPPs ---------------------------------------------------------------

num_ipps: 1

# ------------------------------------------------------------------------------
# Holistic Energy Model (HEM) model-wide options
# ------------------------------------------------------------------------------

# CHOOSE ONE
market_structure: "wholesale_market", "vertically_integrated_utility"
# CHOOSE ONE
der_use_case: "der_use_case", "null_use_case"
# CHOOSE ONE
supply_choice_use_case: "supply_choice_use_case", "null_use_case"

# ------------------------------------------------------------------------------
# Independent Power Producer (IPP) options
# ------------------------------------------------------------------------------

# CHOOSE ONE
ipp_algorithm: "mppdcmer_transportation_storage" # "lagrange_decomposition", "mpppcmer", "miqp"

# ------------------------------------------------------------------------------
# Regulator options
# ------------------------------------------------------------------------------

# CHOOSE ONE
rate_design: "flat_rate", "time_of_use"
# CHOOSE ONE
net_metering_policy: "excess_retail_rate", "excess_marginal_cost", "excess_zero"
