# ------------------------------------------------------------------------------
# Data Selection
# ------------------------------------------------------------------------------

data_selection:
  # Specify the path to the inputs for the model. If using HolisticElectricityModelData.jl, it should point to the test case folder under runs/.
  input_path
# ------------------------------------------------------------------------------
# Simulation Parameters
# ------------------------------------------------------------------------------

simulation_parameters:
  # CHOOSE ONE
  solver: "Xpress", "Gurobi"

# ------------------------------------------------------------------------------
# Holistic Energy Model (HEM) model-wide options
# ------------------------------------------------------------------------------

hem_options:
  # CHOOSE ONE
  market_structure: "wholesale_market" # "vertically_integrated_utility"
  # CHOOSE ONE
  der_use_case: "der_use_case" # "null_use_case"
  # CHOOSE ONE
  supply_choice_use_case: "supply_choice_use_case" # "null_use_case"
  # CHOOSE ONE
  der_aggregation_use_case: "der_aggregation_use_case" # null_use_case

# ------------------------------------------------------------------------------
# Independent Power Producer (IPP) options
# ------------------------------------------------------------------------------

ipp_options:
  # CHOOSE ONE
  ipp_algorithm: "mppdcmer_transportation_storage" # "lagrange_decomposition", "mpppcmer", "miqp"

# ------------------------------------------------------------------------------
# Regulator options
# ------------------------------------------------------------------------------
regulator_options:
  # CHOOSE ONE
  rate_design: "flat_rate" # "time_of_use"
  # CHOOSE ONE
  net_metering_policy: "excess_retail_rate" # "excess_marginal_cost", "excess_zero"

# ------------------------------------------------------------------------------
# Customer options
# ------------------------------------------------------------------------------
customer_options:
  # CHOOSE ONE
  pv_adoption_type: "solar_plus_storage" # "standalone_pv", "compete_standalone_pv_solar_storage"