# ------------------------------------------------------------------------------
# Data Selection
# ------------------------------------------------------------------------------

data_selection: 

# Geography --------------------------------------------------------------------
# Currently, geography is tied to ReEDS balancing areas (BAs). Valid values are
# "p1", "p2", ..., "p134". This map shows where the BAs are located: 
# https://www.nrel.gov/analysis/assets/pdfs/reeds-model-regions-map.pdf.

# HEM analyses have been conducted for:
#     Nevada: "p13", "p14"
#     New England: "p129", "p130", "p131", "p132", "p133", "p134"

  balancing_areas:
    - "p129"
    - "p130"
    - "p131"
    - "p132"
    - "p133"
    - "p134"

# Time -------------------------------------------------------------------------

  base_year: 2020
  num_future_years: 2

# Agent Resolution--------------------------------------------------------------

  num_ipps: 1

# Run Details ------------------------------------------------------------------

# String used to distinguish the input data folder from others
  folder_suffix: "20240806"

# Parse options-----------------------------------------------------------------
  
  der_aggregator: true
  set_nuclear_varcost_negative: true
  sectors_with_county_level_load:
    - "res"
    - "com"
    - "ind"
  # CHOOSE ONE
  load_profiles_subdir: "NewEngland" # Nevada

# Whether the input folder needs to be (re)created
  skip_parse: false

# ------------------------------------------------------------------------------
# Simulation Parameters
# ------------------------------------------------------------------------------

simulation_parameters:
  # CHOOSE ONE
  solver: "Xpress", "Gurobi"

# ------------------------------------------------------------------------------
# Holistic Energy Model (HEM) model-wide options
# ------------------------------------------------------------------------------

hem_options:
  # CHOOSE ONE
  market_structure: "wholesale_market" # "vertically_integrated_utility"
  # CHOOSE ONE
  der_use_case: "der_use_case" # "null_use_case"
  # CHOOSE ONE
  supply_choice_use_case: "supply_choice_use_case" # "null_use_case"
  # CHOOSE ONE
  der_aggregation_use_case: "der_aggregation_use_case" # null_use_case

# ------------------------------------------------------------------------------
# Independent Power Producer (IPP) options
# ------------------------------------------------------------------------------

ipp_options:
  # CHOOSE ONE
  ipp_algorithm: "mppdcmer_transportation_storage" # "lagrange_decomposition", "mpppcmer", "miqp"

# ------------------------------------------------------------------------------
# Regulator options
# ------------------------------------------------------------------------------
regulator_options:
  # CHOOSE ONE
  rate_design: "flat_rate" # "time_of_use"
  # CHOOSE ONE
  net_metering_policy: "excess_retail_rate" # "excess_marginal_cost", "excess_zero"

# ------------------------------------------------------------------------------
# Customer options
# ------------------------------------------------------------------------------
customer_options:
  # CHOOSE ONE
  pv_adoption_type: "solar_plus_storage" # "standalone_pv", "compete_standalone_pv_solar_storage"