# ------------------------------------------------------------------------------
# Data Selection
# ------------------------------------------------------------------------------

DataSelection:
  # Specify the path to the inputs for the model. If using HolisticElectricityModelData.jl, it should point to the test case folder under runs/.
  # If on Windows, enter paths like "C:\\projects\\HolisticElectricityModelData.jl\\runs\\..."
  input_path: "../HolisticElectricityModelData.jl/runs/ba_6_base_2020_future_15_ipps_1/"
  # The base year for the simulation (as set in the input data). If not specified, it defaults to 2020.
  # If you are using a data set with a different base year, you can specify it here.
  year_start: 2020
  # Number of hours per representative hour. If not specified, it defaults to 4.
  # This means that each representative hour represents 4 hours of real time.
  delta_t: 4

# ------------------------------------------------------------------------------
# Run Options
# ------------------------------------------------------------------------------

RunOptions:
  # Specify the output directory for the results. This is optional; if not specified, results will be saved in a newly created directory
  # under the input path with a name based on the configuration.
  output_dir: "Results/"

# ------------------------------------------------------------------------------
# Simulation Parameters
# ------------------------------------------------------------------------------

SimulationParameters:
  # CHOOSE ONE
  solver: "Xpress" # "Gurobi"

# ------------------------------------------------------------------------------
# Holistic Energy Model (HEM) model-wide options
# ------------------------------------------------------------------------------

HEMOptions:
  # CHOOSE ONE WM: Wholesale Market, VIU: Vertically Integrated Utility
  market_structure: "WM" # "VIU"
  # CHOOSE ONE
  der_use_case: "DERAdoption" # "NullUseCase"
  # CHOOSE ONE
  supply_choice_use_case: "SupplyChoice" # "NullUseCase"
  # CHOOSE ONE
  der_aggregation_use_case: "DERAggregation" # NullUseCase

# ------------------------------------------------------------------------------
# Regulator options
# ------------------------------------------------------------------------------
Regulator:
  # CHOOSE ONE
  rate_design: "FlatRate" # "TOU"
  # CHOOSE ONE
  net_metering_policy: "ExcessRetailRate" # "ExcessMarginalCost", "ExcessZero"
  # CHOOSE ONE
  tou_suffix : "NE2025" # "NE2035"
  # OPTIONALLY SET TO NON-DEFAULT VALUE
  planning_reserve_margin : 0.129
  # OPTIONALLY SET TO NON-DEFAULT VALUE
  allowed_return_on_investment : 0.112

# ------------------------------------------------------------------------------
# Independent Power Producer (IPP) options
# ------------------------------------------------------------------------------

IPPGroup:
  # CHOOSE ONE
  ipp_algorithm: "MPPDCMERTransStorage" # "LagrangeDecomposition", "MPPDCMER", "MIQP"

# ------------------------------------------------------------------------------
# Customer options
# ------------------------------------------------------------------------------
CustomerGroup:
  # CHOOSE ONE
  pv_adoption_type: "CompeteDERConfigs" # "StandalonePVOnly", "SolarPlusStorageOnly"

# ------------------------------------------------------------------------------
# DER Aggregator options
# ------------------------------------------------------------------------------
DERAggregator:
  # CHOOSE AN INTEGER 1:5
  incentive_curve: 1
  # CHOOSE A FRACTION [0,1]
  frac_viu_cost_savings_as_revenue: 0.5
  