# Note: please be mindful of underscores. Spaces won't be properly parsed.
# E.g., write "wholesale_market" (with an underscore), not "wholesale market" (with a space).

# Geographical scope
balancing_areas:
  - "p129"
  - "p130"
  - "p131"
  - "p132"
  - "p133"
  - "p134"

# Temporal scope
base_year: 2020
num_future_years: 10

# Holistic Energy Model (HEM) model-wide options
# valid market structures: "wholesale_market", "vertically_integrated_utility"
market_structure: "vertically_integrated_utility"
# valid DER use cases: "der_use_case", "null_use_case"
der_use_case: "der_use_case"
# valid Supply Choice use cases: "supply_choice_use_case", "null_use_case"
supply_choice_use_case: "null_use_case"

# Agent options
# Independent Power Producer (IPP) options
num_ipps: 1
# valid IPP algorithms: "lagrange_decomposition", "mppdcmer_transportation_storage", "mpppcmer", "miqp"
ipp_algorithm: "mppdcmer_transportation_storage"

# Regulator options
# valid Rate Designs: "flat_rate", "time_of_use"
rate_design: "flat_rate"
# valid Net Metering Policies: "excess_retail_rate", "excess_marginal_cost", "excess_zero"
net_metering_policy: "excess_retail_rate"

# Solver
# valid solvers: "Gurobi", "Xpress"
solver: "Gurobi"
